# This dockerfile intended to run the Signaling Server under GraalVM with an agentlib for 
# produce native image configuration files for later usage on a native image build.
# Produced json files must be located at src/main/resources/META-INF/native-image/org.fabri1983.signaling folder in the Signaling project. 
 
######################################################################################################
FROM oracle/graalvm-ce:20.0.0-java11 AS STAGING-APP
ARG DEPENDENCIES=docker-workdir

RUN mkdir -p /staging/app/

# Stage dependencies and classes
COPY ${DEPENDENCIES}/META-INF             /staging/app/META-INF
COPY ${DEPENDENCIES}/BOOT-INF             /staging/app/BOOT-INF


######################################################################################################
FROM oracle/graalvm-ce:20.0.0-java11
ARG JAVA_MAIN_CLASS

ENV ENV_JAVA_MAIN_CLASS=${JAVA_MAIN_CLASS}

RUN gu install native-image \
    && mkdir -p /app/native-config

# Copy staged decompressed JAR from previous stage
COPY --from=STAGING-APP /staging/app  /app

# Entry with exec so jvm flags are correctly gathered
ENTRYPOINT exec java -agentlib:native-image-agent=config-output-dir=native-config/ \
   -cp /app/BOOT-INF/classes:/app/BOOT-INF/lib/* ${ENV_JAVA_MAIN_CLASS}
